services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ./ollama/data:/root/.ollama
      - ./ollama/init:/init
    environment:
      - OLLAMA_KEEP_ALIVE=-1
      - OLLAMA_DEBUG=2
      - OLLAMA_NUM_PARALLEL=2
      - OLLAMA_MAX_LOADED_MODELS=2
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    entrypoint: [ "/bin/sh", "/init/run_ollama.sh" ]
    
  db:
    build:
      context: ./db
    container_name: db
    ports:
      - 15432:5432
    environment:
      - POSTGRES_USER=ai-diary
      - POSTGRES_PASSWORD=not-secure
      - POSTGRES_DB=ai-diary
      - POSTGRES_HOST_AUTH_METHOD=trust
      - PGDATA=/var/lib/postgresql/data/pgdata
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ai-diary -d ai-diary"]
      interval: 5s
      timeout: 3s
      retries: 5
    volumes:
      - ./db/data/:/var/lib/postgresql/data/
      - ./db/init:/docker-entrypoint-initdb.d

  backend:
    build:
      context: ./backend/
    container_name: backend
    depends_on:
      db:
        condition: service_healthy
      ollama:
        condition: service_started
    environment:
      - QUARKUS_DATASOURCE_USERNAME=ai-diary
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://db:5432/ai-diary
      - OLLAMA_HOST=http://ollama:11434
      - QUARKUS_LANGCHAIN4J_OLLAMA_BASE-URL=http://ollama:11434
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    depends_on:
      backend:
        condition: service_started
    environment:
      - BACKEND_URL=http://backend:8080
    ports:
      - "8081:8081"